/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Telas;

/**
 *
 * @author Ian
 */
import javax.swing.JOptionPane;
import DAO.*;
import Modelo.*;
public class TelaPrincipal extends javax.swing.JFrame {
private FuncionarioDAO daoFuncionarios = new FuncionarioDAO();
private UsuarioDAO daoUsuarios = new UsuarioDAO();
private GerenciarFuncio telaGerenciarFuncio;
private GerenciarUsuario telaGerenciarUsuario;
private GerenciarLivros telaGerenciarLivros;
private GerenciarAutores telaGerenciarAutores;
private GerenciarCategorias telaGerenciarCategorias;
private LoginFuncionario telaLoginFuncionario;
private LoginUsuario telaLoginUsuario;
private MenuFuncionario telaMenuFuncionario;
private MenuUsuario telaMenuUsuario;
private AutorDAO daoAutor = new AutorDAO();
private CategoriaDAO daoCategoria = new CategoriaDAO();
private EmprestimoDAO daoEmprestimo = new EmprestimoDAO();
private LivroDAO daoLivro = new LivroDAO();
private MenuAdmin telaMenuAdmin;
    /**
     * Creates new form TelaPrincipal
     */
    public TelaPrincipal() {
        initComponents();
    }
     public TelaPrincipal(FuncionarioDAO daoFuncionarios,UsuarioDAO daoUsuarios,LivroDAO daoLivro, EmprestimoDAO daoEmprestimo, AutorDAO daoAutor){
        this();        
        this.daoFuncionarios = daoFuncionarios;
        this.daoUsuarios = daoUsuarios;
        this.daoLivro= daoLivro;
        this.daoEmprestimo=daoEmprestimo;
        this.daoAutor=daoAutor;        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        textologin = new javax.swing.JTextField();
        textoFuncio = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        buttologin = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        textoSenha = new javax.swing.JPasswordField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        textologin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textologinActionPerformed(evt);
            }
        });

        textoFuncio.setText("Login:");

        jLabel2.setText("Senha:");

        buttologin.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        buttologin.setText("Entrar");
        buttologin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttologinActionPerformed(evt);
            }
        });

        jLabel3.setText("SISTEMA DE GERENCIAMENTO");

        jButton1.setText("Sair");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Logar como Funcionario");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Logar como Usuario");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        jLabel1.setText("Logar como Administrador");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(185, 185, 185)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(buttologin, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(6, 6, 6)
                        .addComponent(textoSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 291, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jButton1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton2)
                        .addGap(90, 90, 90)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(textoFuncio)
                        .addGap(13, 13, 13)
                        .addComponent(textologin, javax.swing.GroupLayout.PREFERRED_SIZE, 294, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(185, 185, 185))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(74, 74, 74)
                .addComponent(jLabel3)
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(jButton3))
                .addGap(51, 51, 51)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textologin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textoFuncio))
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(textoSenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(49, 49, 49)
                .addComponent(buttologin, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(jButton1)
                .addGap(72, 72, 72))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttologinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttologinActionPerformed
        //Botão de login
        if(textologin.getText().equals("admin") && textoSenha.getText().equals("admin")){
            
            this.setEnabled(false);
            dispose();            
            abrirTelaMenuAdmin(this,daoFuncionarios,daoUsuarios,daoLivro,daoEmprestimo,daoAutor);
            //new MenuAdmin(this).setVisible(true);
        } else {
            JOptionPane.showMessageDialog(null, "Login invalido!");
        }

        // TODO add your handling code here:
    }//GEN-LAST:event_buttologinActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        //Botão de sair
        System.exit(0);// TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void textologinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textologinActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textologinActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        dispose();
        abrirTelaLoginFuncionario(this,daoFuncionarios,daoUsuarios,daoLivro,daoEmprestimo,daoAutor);
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
       //Logar como usuario
       dispose();
       abrirTelaLoginUsuario(this,daoFuncionarios,daoUsuarios,daoLivro,daoEmprestimo,daoAutor);
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPrincipal().setVisible(true);
            }
        });
    }
    
    public  void abrirTelaGerenciarFuncio(TelaPrincipal tela, FuncionarioDAO daoFuncionario,UsuarioDAO daoUsuarios,LivroDAO daoLivro, EmprestimoDAO daoEmprestimo, AutorDAO daoAutor) {
        telaGerenciarFuncio = new GerenciarFuncio(tela,daoFuncionarios,daoUsuarios,daoLivro,daoEmprestimo,daoAutor);
        //telaGerenciarFuncio.setDaoFuncionarios(daoFuncionarios);
        telaGerenciarFuncio.setVisible(true);
    }
    public  void abrirTelaMenuAdmin(TelaPrincipal tela, FuncionarioDAO daoFuncionario,UsuarioDAO daoUsuarios,LivroDAO daoLivro, EmprestimoDAO daoEmprestimo, AutorDAO daoAutor) {
        telaMenuAdmin = new MenuAdmin(tela,daoFuncionarios,daoUsuarios,daoLivro,daoEmprestimo,daoAutor);
        //telaGerenciarFuncio.setDaoFuncionarios(daoFuncionarios);
        telaMenuAdmin.setVisible(true);
    }
    public  void abrirTelaGerenciarUsuario(TelaPrincipal tela, FuncionarioDAO daoFuncionario,UsuarioDAO daoUsuarios,LivroDAO daoLivro, EmprestimoDAO daoEmprestimo, AutorDAO daoAutor) {
        telaGerenciarUsuario = new GerenciarUsuario(tela,daoFuncionarios,daoUsuarios,daoLivro,daoEmprestimo,daoAutor);
        //telaGerenciarFuncio.setDaoFuncionarios(daoFuncionarios);
        telaGerenciarUsuario.setVisible(true);
    }
    public  void abrirTelaGerenciarLivros(TelaPrincipal tela, FuncionarioDAO daoFuncionario,UsuarioDAO daoUsuarios,LivroDAO daoLivro, EmprestimoDAO daoEmprestimo, AutorDAO daoAutor) {
        telaGerenciarLivros = new GerenciarLivros(tela,daoFuncionarios,daoUsuarios,daoLivro,daoEmprestimo,daoAutor);
        //telaGerenciarFuncio.setDaoFuncionarios(daoFuncionarios);
        telaGerenciarLivros.setVisible(true);
    }
    public  void abrirTelaGerenciarAutores(TelaPrincipal tela, FuncionarioDAO daoFuncionario,UsuarioDAO daoUsuarios,LivroDAO daoLivro, EmprestimoDAO daoEmprestimo, AutorDAO daoAutor) {
        telaGerenciarAutores = new GerenciarAutores(tela,daoFuncionarios,daoUsuarios,daoLivro,daoEmprestimo,daoAutor);
        //telaGerenciarFuncio.setDaoFuncionarios(daoFuncionarios);
        telaGerenciarAutores.setVisible(true);
    }
    public  void abrirTelaGerenciarCategoias(TelaPrincipal tela, FuncionarioDAO daoFuncionario,UsuarioDAO daoUsuarios,LivroDAO daoLivro, EmprestimoDAO daoEmprestimo, AutorDAO daoAutor) {
        telaGerenciarCategorias = new GerenciarCategorias(tela,daoFuncionarios,daoUsuarios,daoLivro,daoEmprestimo,daoAutor);
        //telaGerenciarFuncio.setDaoFuncionarios(daoFuncionarios);
        telaGerenciarCategorias.setVisible(true);
    }
    public  void abrirTelaPrincipal(TelaPrincipal tela, FuncionarioDAO daoFuncionario,UsuarioDAO daoUsuarios,LivroDAO daoLivro, EmprestimoDAO daoEmprestimo, AutorDAO daoAutor) {
        new TelaPrincipal(daoFuncionarios,daoUsuarios,daoLivro,daoEmprestimo,daoAutor).setVisible(true);
        //telaGerenciarFuncio.setDaoFuncionarios(daoFuncionarios);
        
    }
    public  void abrirTelaLoginFuncionario(TelaPrincipal tela, FuncionarioDAO daoFuncionario,UsuarioDAO daoUsuarios,LivroDAO daoLivro, EmprestimoDAO daoEmprestimo, AutorDAO daoAutor) {
        telaLoginFuncionario = new LoginFuncionario(tela,daoFuncionarios,daoUsuarios,daoLivro,daoEmprestimo,daoAutor);
        //telaGerenciarFuncio.setDaoFuncionarios(daoFuncionarios);
        telaLoginFuncionario.setVisible(true);
    }
    public  void abrirTelaMenuFuncionario(TelaPrincipal tela, FuncionarioDAO daoFuncionario,UsuarioDAO daoUsuarios,LivroDAO daoLivro, EmprestimoDAO daoEmprestimo, AutorDAO daoAutor,Funcionario FuncionarioAtual) {
        telaMenuFuncionario = new MenuFuncionario(tela,daoFuncionarios,daoUsuarios,daoLivro,daoEmprestimo,daoAutor,FuncionarioAtual);
        //telaGerenciarFuncio.setDaoFuncionarios(daoFuncionarios);
        telaMenuFuncionario.setVisible(true);
    }
    public  void abrirTelaMenuUsuario(TelaPrincipal tela, FuncionarioDAO daoFuncionario,UsuarioDAO daoUsuarios,LivroDAO daoLivro, EmprestimoDAO daoEmprestimo, AutorDAO daoAutor) {
        telaMenuUsuario = new MenuUsuario(tela,daoFuncionarios,daoUsuarios,daoLivro,daoEmprestimo,daoAutor);
        //telaGerenciarFuncio.setDaoFuncionarios(daoFuncionarios);
        telaMenuUsuario.setVisible(true);
    }
    public  void abrirTelaLoginUsuario(TelaPrincipal tela, FuncionarioDAO daoFuncionario,UsuarioDAO daoUsuarios,LivroDAO daoLivro, EmprestimoDAO daoEmprestimo, AutorDAO daoAutor) {
        telaLoginUsuario = new LoginUsuario(tela,daoFuncionarios,daoUsuarios,daoLivro,daoEmprestimo,daoAutor);
        //telaGerenciarFuncio.setDaoFuncionarios(daoFuncionarios);
        telaLoginUsuario.setVisible(true);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttologin;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel textoFuncio;
    private javax.swing.JPasswordField textoSenha;
    private javax.swing.JTextField textologin;
    // End of variables declaration//GEN-END:variables
}
